spring:
    data:
        mongodb:
            host: ds121896.mlab.com
            port: 21896
            database: camposdeguerra
            username: root
            password: root
    redis:
        host: 34.214.90.42
        port: 6379
        #password:
